#!/usr/bin/env bash

# This script will create a single file from the given directory
# and its subdirectories. The file will contain all the text files
# in the directory and its subdirectories.
game_dir="fdchallenge2"
output_file="${game_dir}_lit.ink"
main_file="${game_dir}/My Damn Money.ink"

# Remove the output file if it exists
if [ -f $output_file ]; then
  rm $output_file
fi
# remove the tmp file if it exists
if [ -f $output_file.tmp ]; then
  rm $output_file.tmp
fi

#  Lastly, add the main file
( echo -e "\n// BEGIN ${main_file}"; grep -ve "^INCLUDE" "${main_file}"; echo -e "\n// END ${main_file}") >> $output_file.tmp

# Grep all the INCLUDE lines in the main file
# and add them to the output file
grep "^INCLUDE" "${main_file}" | while read -r line; do
  file=$(echo $line | cut -d' ' -f2)
  (echo -e "// BEGIN ${file}"; cat "${game_dir}/${file}"; echo -e "\n// END ${file}") >> $output_file.tmp
done




# Extract all the CONST lines from the tmp file and add them to the output file
grep "^\ *CONST" $output_file.tmp > $output_file.CONST

# remove the CONST lines from the tmp file
grep -ve "^\ *CONST" $output_file.tmp > $output_file.tmp.NO_CONST
mv $output_file.tmp.NO_CONST $output_file.tmp

# Now, extract all the LIST lines from the tmp file and add them to the output file
grep "^\ *LIST" $output_file.tmp  > $output_file.LIST


# remove the LIST lines from the tmp file
grep -ve "^\ *LIST" $output_file.tmp > $output_file.tmp.NO_LIST
mv $output_file.tmp.NO_LIST $output_file.tmp

# Now, extract all the VAR lines from the tmp file and add them to the output file
grep "^\ *VAR" $output_file.tmp > $output_file.VAR


# remove the VAR lines from the tmp file
grep -ve "^\ *VAR" $output_file.tmp > $output_file.tmp.NO_VAR
mv $output_file.tmp.NO_VAR $output_file.tmp

cat <<EOH > "${output_file}"
/* ----------------------------------------
  Generated by make_single_file.sh
  on $(date)
  Main file: $main_file
---------------------------------------- */
EOH

cat $output_file.CONST $output_file.LIST $output_file.VAR >> ${output_file}

# echo -e "\n-> main\n" >> $output_file
cat $output_file.tmp >> ${output_file}

# remove b, i, p, u, s tags
sed -i '' 's/<[bipus]>//g' ${output_file}
sed -i  '' 's/<\/[bipus]>//g' ${output_file}

# Replace <br> with space
sed -i '' 's/<br>/\ /g' ${output_file}

sed -i '' 's/_LITEROTICA_EXPORT\ =\ false/_LITEROTICA_EXPORT\ =\ true/g' ${output_file}

rm $output_file.tmp $output_file.CONST $output_file.LIST $output_file.VAR
